/* imports_osmos.c -- resolver table for libosmos.so
 *
 * GENERATED by tools/gen_imports.py. Re-run tools/verify_imports.py against
 * your own copy of the library after any edit; it fails on any symbol the
 * table does not cover.
 *
 * libosmos.so is linked BIND_NOW (DT_FLAGS = NOW), so every entry below has to
 * resolve before the first call into the module. There is no lazy PLT to catch
 * a mistake later: a gap is a load-time abort, which is the behaviour we want.
 *
 * Coverage: 279 symbols
 *    53  GL / EGL          -> switch-mesa
 *    26  OpenAL            -> osmos_al.c (our own mixer over audren)
 *    37  hand-written      -> osmos_shim.c
 *   151  bionic shims      -> reused from the reference ports
 *    12  newlib passthrough
 */

#define _GNU_SOURCE

#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <stdarg.h>
#include <string.h>
#include <strings.h>
#include <malloc.h>
#include <unistd.h>
#include <fcntl.h>
#include <ctype.h>
#include <math.h>
#include <pthread.h>
#include <time.h>
#include <wchar.h>
#include <wctype.h>
#include <errno.h>
#include <locale.h>
#include <setjmp.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <dirent.h>

/* Deliberately NOT included: <syslog.h>. It is a glibc header; devkitA64's
 * newlib does not ship it. openlog/syslog/closelog resolve to no-op shims. */

#include <EGL/egl.h>
#include <GLES2/gl2.h>
#include <switch.h>

#include "so_util.h"
#include "util.h"
#include "libc_shim.h"
#include "osmos_al.h"
#include "osmos_shim.h"
#include "osmos_diag.h"
#include "osmos_io.h"
#include "osmos_gl.h"
#include "imports_helpers.h"

DynLibFunction dynlib_functions[] = {
  /* --- GL / EGL -- switch-mesa (53) --- */
  { "glActiveTexture",            (uintptr_t)&glActiveTexture },
  { "glAttachShader",             (uintptr_t)&glAttachShader },
  { "glBindAttribLocation",       (uintptr_t)&glBindAttribLocation },
  { "glBindBuffer",               (uintptr_t)&glBindBuffer },
  { "glBindFramebuffer",          (uintptr_t)&glBindFramebuffer_diag },
  { "glBindTexture",              (uintptr_t)&glBindTexture },
  { "glBlendFunc",                (uintptr_t)&glBlendFunc_diag },
  { "glBufferData",               (uintptr_t)&glBufferData },
  { "glCheckFramebufferStatus",   (uintptr_t)&glCheckFramebufferStatus },
  { "glClear",                    (uintptr_t)&glClear_diag },
  { "glClearColor",               (uintptr_t)&glClearColor_diag },
  { "glColorMask",                (uintptr_t)&glColorMask_diag },
  { "glCompileShader",            (uintptr_t)&glCompileShader },
  { "glCreateProgram",            (uintptr_t)&glCreateProgram },
  { "glCreateShader",             (uintptr_t)&glCreateShader },
  { "glDeleteBuffers",            (uintptr_t)&glDeleteBuffers },
  { "glDeleteProgram",            (uintptr_t)&glDeleteProgram },
  { "glDeleteShader",             (uintptr_t)&glDeleteShader },
  { "glDeleteTextures",           (uintptr_t)&glDeleteTextures },
  { "glDepthMask",                (uintptr_t)&glDepthMask },
  { "glDetachShader",             (uintptr_t)&glDetachShader },
  { "glDisable",                  (uintptr_t)&glDisable_diag },
  { "glDisableVertexAttribArray", (uintptr_t)&glDisableVertexAttribArray },
  { "glDrawArrays",               (uintptr_t)&glDrawArrays_diag },
  { "glEnable",                   (uintptr_t)&glEnable_diag },
  { "glEnableVertexAttribArray",  (uintptr_t)&glEnableVertexAttribArray },
  { "glFramebufferTexture2D",     (uintptr_t)&glFramebufferTexture2D },
  { "glGenBuffers",               (uintptr_t)&glGenBuffers },
  { "glGenFramebuffers",          (uintptr_t)&glGenFramebuffers },
  { "glGenTextures",              (uintptr_t)&glGenTextures },
  { "glGenerateMipmap",           (uintptr_t)&glGenerateMipmap },
  { "glGetIntegerv",              (uintptr_t)&glGetIntegerv },
  { "glGetProgramInfoLog",        (uintptr_t)&glGetProgramInfoLog },
  { "glGetProgramiv",             (uintptr_t)&glGetProgramiv },
  { "glGetShaderInfoLog",         (uintptr_t)&glGetShaderInfoLog },
  { "glGetShaderiv",              (uintptr_t)&glGetShaderiv },
  { "glGetString",                (uintptr_t)&glGetString },
  { "glGetUniformLocation",       (uintptr_t)&glGetUniformLocation },
  { "glHint",                     (uintptr_t)&glHint },
  { "glLineWidth",                (uintptr_t)&glLineWidth },
  { "glLinkProgram",              (uintptr_t)&glLinkProgram },
  { "glShaderSource",             (uintptr_t)&glShaderSource },
  { "glTexImage2D",               (uintptr_t)&glTexImage2D },
  { "glTexParameterf",            (uintptr_t)&glTexParameterf },
  { "glTexParameteri",            (uintptr_t)&glTexParameteri },
  { "glUniform1f",                (uintptr_t)&glUniform1f },
  { "glUniform1i",                (uintptr_t)&glUniform1i },
  { "glUniform4f",                (uintptr_t)&glUniform4f_diag },
  { "glUniform4fv",               (uintptr_t)&glUniform4fv_diag },
  { "glUniformMatrix4fv",         (uintptr_t)&glUniformMatrix4fv_diag },
  { "glUseProgram",               (uintptr_t)&glUseProgram },
  { "glVertexAttribPointer",      (uintptr_t)&glVertexAttribPointer },
  { "glViewport",                 (uintptr_t)&glViewport_diag },

  /* --- OpenAL -- osmos_al.c (26) --- */
  { "alBufferData",           (uintptr_t)&alBufferData },
  { "alDeleteBuffers",        (uintptr_t)&alDeleteBuffers },
  { "alDeleteSources",        (uintptr_t)&alDeleteSources },
  { "alGenBuffers",           (uintptr_t)&alGenBuffers },
  { "alGenSources",           (uintptr_t)&alGenSources },
  { "alGetError",             (uintptr_t)&alGetError },
  { "alGetSourcef",           (uintptr_t)&alGetSourcef },
  { "alGetSourcei",           (uintptr_t)&alGetSourcei },
  { "alListenerfv",           (uintptr_t)&alListenerfv },
  { "alSourcePause",          (uintptr_t)&alSourcePause },
  { "alSourcePlay",           (uintptr_t)&alSourcePlay },
  { "alSourceQueueBuffers",   (uintptr_t)&alSourceQueueBuffers },
  { "alSourceStop",           (uintptr_t)&alSourceStop },
  { "alSourceUnqueueBuffers", (uintptr_t)&alSourceUnqueueBuffers },
  { "alSourcef",              (uintptr_t)&alSourcef },
  { "alSourcei",              (uintptr_t)&alSourcei },
  { "alcCloseDevice",         (uintptr_t)&alcCloseDevice },
  { "alcCreateContext",       (uintptr_t)&alcCreateContext },
  { "alcDestroyContext",      (uintptr_t)&alcDestroyContext },
  { "alcGetContextsDevice",   (uintptr_t)&alcGetContextsDevice },
  { "alcGetCurrentContext",   (uintptr_t)&alcGetCurrentContext },
  { "alcGetJavaVM",           (uintptr_t)&alcGetJavaVM },
  { "alcMakeContextCurrent",  (uintptr_t)&alcMakeContextCurrent },
  { "alcOpenDevice",          (uintptr_t)&alcOpenDevice },
  { "alcProcessContext",      (uintptr_t)&alcProcessContext },
  { "alcSuspendContext",      (uintptr_t)&alcSuspendContext },

  /* --- hand-written shims -- osmos_shim.c (37) --- */
  { "acos",          (uintptr_t)&acos },
  { "atan",          (uintptr_t)&atan },
  { "atanf",         (uintptr_t)&atanf },
  { "clock_getres",  (uintptr_t)&clock_getres_fake },
  { "cos",           (uintptr_t)&cos },
  { "ctime",         (uintptr_t)&ctime },
  { "exp",           (uintptr_t)&exp },
  { "exp2f",         (uintptr_t)&exp2f },
  { "fputws",        (uintptr_t)&fputws },
  { "isdigit_l",     (uintptr_t)&isdigit_l_fake },
  { "islower_l",     (uintptr_t)&islower_l_fake },
  { "isupper_l",     (uintptr_t)&isupper_l_fake },
  { "isxdigit_l",    (uintptr_t)&isxdigit_l_fake },
  { "ldexp",         (uintptr_t)&ldexp },
  { "log",           (uintptr_t)&log },
  { "mbstowcs",      (uintptr_t)&mbstowcs },
  { "modff",         (uintptr_t)&modff },
  { "pthread_equal", (uintptr_t)&pthread_equal },
  { "sin",           (uintptr_t)&sin },
  { "sincos",        (uintptr_t)&sincos_fake },
  { "sincosf",       (uintptr_t)&sincosf_fake },
  { "strcasecmp",    (uintptr_t)&strcasecmp },
  { "tolower_l",     (uintptr_t)&tolower_l_fake },
  { "toupper_l",     (uintptr_t)&toupper_l_fake },
  { "vswprintf",     (uintptr_t)&vswprintf },
  { "wcscat",        (uintptr_t)&wcscat },
  { "wcschr",        (uintptr_t)&wcschr },
  { "wcscmp",        (uintptr_t)&wcscmp },
  { "wcscpy",        (uintptr_t)&wcscpy },
  { "wcsncpy",       (uintptr_t)&wcsncpy },
  { "wcsrchr",       (uintptr_t)&wcsrchr },
  { "wcsstr",        (uintptr_t)&wcsstr },
  { "wcstombs",      (uintptr_t)&wcstombs },
  { "wmemcpy",       (uintptr_t)&wmemcpy },
  { "wmemmove",      (uintptr_t)&wmemmove },
  { "wmemset",       (uintptr_t)&wmemset },
  { "wprintf",       (uintptr_t)&wprintf },

  /* --- bionic shims reused from the reference ports (151) --- */
  { "__ctype_get_mb_cur_max",    (uintptr_t)&__ctype_get_mb_cur_max_fake },
  { "__cxa_atexit",              (uintptr_t)&__cxa_atexit_fake },
  { "__cxa_finalize",            (uintptr_t)&__cxa_finalize_fake },
  { "__errno",                   (uintptr_t)&__errno },
  { "__memcpy_chk",              (uintptr_t)&__memcpy_chk_fake },
  { "__memmove_chk",             (uintptr_t)&__memmove_chk_fake },
  { "__open_2",                  (uintptr_t)&__open_2_diag },
  { "__sF",                      (uintptr_t)&fake_sF },
  { "__stack_chk_fail",          (uintptr_t)&__stack_chk_fail_fake },
  { "__strlen_chk",              (uintptr_t)&__strlen_chk_fake },
  { "__system_property_get",     (uintptr_t)&__system_property_get_fake },
  { "__vsnprintf_chk",           (uintptr_t)&__vsnprintf_chk_fake },
  { "abort",                     (uintptr_t)&abort },
  { "acosf",                     (uintptr_t)&acosf },
  { "android_set_abort_message", (uintptr_t)&android_set_abort_message_fake },
  { "asinf",                     (uintptr_t)&asinf },
  { "atan2f",                    (uintptr_t)&atan2f },
  { "btowc",                     (uintptr_t)&btowc },
  { "calloc",                    (uintptr_t)&calloc },
  { "clock_gettime",             (uintptr_t)&clock_gettime_bionic },
  { "closelog",                  (uintptr_t)&ret0_i },
  { "cosf",                      (uintptr_t)&cosf },
  { "dl_iterate_phdr",           (uintptr_t)&so_dl_iterate_phdr },
  { "exit",                      (uintptr_t)&osmos_exit },
  { "expf",                      (uintptr_t)&expf },
  { "fflush",                    (uintptr_t)&fflush_fake },
  { "fmodf",                     (uintptr_t)&fmodf },
  { "fprintf",                   (uintptr_t)&fprintf_fake },
  { "fputc",                     (uintptr_t)&fputc_fake },
  { "free",                      (uintptr_t)&free },
  { "freelocale",                (uintptr_t)&freelocale_fake },
  { "fstat",                     (uintptr_t)&fstat_fake },
  { "getauxval",                 (uintptr_t)&getauxval_fake },
  { "getenv",                    (uintptr_t)&getenv_fake },
  { "iswalpha_l",                (uintptr_t)&iswalpha_l_fake },
  { "iswblank_l",                (uintptr_t)&iswblank_l_fake },
  { "iswcntrl_l",                (uintptr_t)&iswcntrl_l_fake },
  { "iswdigit_l",                (uintptr_t)&iswdigit_l_fake },
  { "iswlower_l",                (uintptr_t)&iswlower_l_fake },
  { "iswprint_l",                (uintptr_t)&iswprint_l_fake },
  { "iswpunct_l",                (uintptr_t)&iswpunct_l_fake },
  { "iswspace_l",                (uintptr_t)&iswspace_l_fake },
  { "iswupper_l",                (uintptr_t)&iswupper_l_fake },
  { "iswxdigit_l",               (uintptr_t)&iswxdigit_l_fake },
  { "localeconv",                (uintptr_t)&localeconv },
  { "logf",                      (uintptr_t)&logf },
  { "longjmp",                   (uintptr_t)&longjmp },
  { "malloc",                    (uintptr_t)&malloc_diag },
  { "mbrlen",                    (uintptr_t)&mbrlen },
  { "mbrtowc",                   (uintptr_t)&mbrtowc },
  { "mbsnrtowcs",                (uintptr_t)&mbsnrtowcs_fake },
  { "mbsrtowcs",                 (uintptr_t)&mbsrtowcs },
  { "mbtowc",                    (uintptr_t)&mbtowc },
  { "memchr",                    (uintptr_t)&memchr },
  { "memcmp",                    (uintptr_t)&memcmp },
  { "memcpy",                    (uintptr_t)&memcpy },
  { "memmove",                   (uintptr_t)&memmove },
  { "memset",                    (uintptr_t)&memset },
  { "mmap",                      (uintptr_t)&osmos_mmap },
  { "munmap",                    (uintptr_t)&osmos_munmap },
  { "nanosleep",                 (uintptr_t)&nanosleep },
  { "newlocale",                 (uintptr_t)&newlocale_fake },
  { "openlog",                   (uintptr_t)&ret0_i },
  { "posix_memalign",            (uintptr_t)&posix_memalign_fake },
  { "pow",                       (uintptr_t)&pow },
  { "powf",                      (uintptr_t)&powf },
  { "pthread_cond_broadcast",    (uintptr_t)&pthread_cond_broadcast_fake },
  { "pthread_cond_destroy",      (uintptr_t)&pthread_cond_destroy_fake },
  { "pthread_cond_signal",       (uintptr_t)&pthread_cond_signal_fake },
  { "pthread_cond_timedwait",    (uintptr_t)&pthread_cond_timedwait_fake },
  { "pthread_cond_wait",         (uintptr_t)&pthread_cond_wait_fake },
  { "pthread_create",            (uintptr_t)&pthread_create_fake },
  { "pthread_detach",            (uintptr_t)&pthread_detach },
  { "pthread_getspecific",       (uintptr_t)&pthread_getspecific_fake },
  { "pthread_join",              (uintptr_t)&pthread_join_fake },
  { "pthread_key_create",        (uintptr_t)&pthread_key_create_fake },
  { "pthread_key_delete",        (uintptr_t)&pthread_key_delete_fake },
  { "pthread_mutex_destroy",     (uintptr_t)&pthread_mutex_destroy_fake },
  { "pthread_mutex_init",        (uintptr_t)&pthread_mutex_init_fake },
  { "pthread_mutex_lock",        (uintptr_t)&pthread_mutex_lock_fake },
  { "pthread_mutex_trylock",     (uintptr_t)&pthread_mutex_trylock_fake },
  { "pthread_mutex_unlock",      (uintptr_t)&pthread_mutex_unlock_fake },
  { "pthread_mutexattr_destroy", (uintptr_t)&ret0_i },
  { "pthread_mutexattr_init",    (uintptr_t)&pthread_mutexattr_init_fake },
  { "pthread_mutexattr_settype", (uintptr_t)&pthread_mutexattr_settype_fake },
  { "pthread_once",              (uintptr_t)&pthread_once_fake },
  { "pthread_rwlock_rdlock",     (uintptr_t)&pthread_rwlock_rdlock_fake },
  { "pthread_rwlock_unlock",     (uintptr_t)&pthread_rwlock_unlock_fake },
  { "pthread_rwlock_wrlock",     (uintptr_t)&pthread_rwlock_wrlock_fake },
  { "pthread_self",              (uintptr_t)&pthread_self },
  { "pthread_setspecific",       (uintptr_t)&pthread_setspecific_fake },
  { "qsort",                     (uintptr_t)&qsort },
  { "realloc",                   (uintptr_t)&realloc },
  { "sched_yield",               (uintptr_t)&sched_yield_diag },
  { "setjmp",                    (uintptr_t)&setjmp },
  { "setlocale",                 (uintptr_t)&setlocale_bionic },
  { "signal",                    (uintptr_t)&signal_stub },
  { "sinf",                      (uintptr_t)&sinf },
  { "snprintf",                  (uintptr_t)&snprintf },
  { "sscanf",                    (uintptr_t)&sscanf },
  { "stat",                      (uintptr_t)&stat_fake },
  { "strcat",                    (uintptr_t)&strcat },
  { "strcmp",                    (uintptr_t)&z_strcmp },
  { "strcoll_l",                 (uintptr_t)&strcoll_l_fake },
  { "strcpy",                    (uintptr_t)&strcpy },
  { "strerror_r",                (uintptr_t)&strerror_r_fake },
  { "strftime_l",                (uintptr_t)&strftime_l_fake },
  { "strlen",                    (uintptr_t)&z_strlen },
  { "strncmp",                   (uintptr_t)&z_strncmp },
  { "strncpy",                   (uintptr_t)&strncpy },
  { "strrchr",                   (uintptr_t)&z_strrchr },
  { "strstr",                    (uintptr_t)&z_strstr },
  { "strtod",                    (uintptr_t)&strtod },
  { "strtof",                    (uintptr_t)&strtof },
  { "strtol",                    (uintptr_t)&strtol },
  { "strtold",                   (uintptr_t)&strtold },
  { "strtold_l",                 (uintptr_t)&strtold_l_fake },
  { "strtoll",                   (uintptr_t)&strtoll },
  { "strtoll_l",                 (uintptr_t)&strtoll_l_fake },
  { "strtoul",                   (uintptr_t)&strtoul },
  { "strtoull",                  (uintptr_t)&strtoull },
  { "strtoull_l",                (uintptr_t)&strtoull_l_fake },
  { "strxfrm_l",                 (uintptr_t)&strxfrm_l_fake },
  { "swprintf",                  (uintptr_t)&swprintf },
  { "syscall",                   (uintptr_t)&syscall_fake },
  { "sysconf",                   (uintptr_t)&sysconf_pass },
  { "syslog",                    (uintptr_t)&ret0_i },
  { "tanf",                      (uintptr_t)&tanf },
  { "time",                      (uintptr_t)&time },
  { "towlower_l",                (uintptr_t)&towlower_l_fake },
  { "towupper_l",                (uintptr_t)&towupper_l_fake },
  { "uselocale",                 (uintptr_t)&uselocale_fake },
  { "vasprintf",                 (uintptr_t)&vasprintf },
  { "vfprintf",                  (uintptr_t)&vfprintf_fake },
  { "vsnprintf",                 (uintptr_t)&vsnprintf },
  { "vsscanf",                   (uintptr_t)&vsscanf },
  { "wcrtomb",                   (uintptr_t)&wcrtomb },
  { "wcscoll_l",                 (uintptr_t)&wcscoll_l_fake },
  { "wcslen",                    (uintptr_t)&wcslen },
  { "wcsnrtombs",                (uintptr_t)&wcsnrtombs_fake },
  { "wcstod",                    (uintptr_t)&wcstod },
  { "wcstof",                    (uintptr_t)&wcstof },
  { "wcstol",                    (uintptr_t)&wcstol },
  { "wcstold",                   (uintptr_t)&wcstold },
  { "wcstoll",                   (uintptr_t)&wcstoll },
  { "wcstoul",                   (uintptr_t)&wcstoul },
  { "wcstoull",                  (uintptr_t)&wcstoull },
  { "wcsxfrm_l",                 (uintptr_t)&wcsxfrm_l_fake },
  { "wctob",                     (uintptr_t)&wctob },
  { "wmemchr",                   (uintptr_t)&wmemchr },
  { "wmemcmp",                   (uintptr_t)&wmemcmp },

  /* --- straight through to newlib (12) --- */
  { "close",  (uintptr_t)&close_locked },
  { "fclose", (uintptr_t)&fclose_locked },
  { "fcntl",  (uintptr_t)&fcntl },
  { "fopen",  (uintptr_t)&fopen_diag },
  { "fread",  (uintptr_t)&fread_diag },
  { "fseek",  (uintptr_t)&fseek_locked },
  { "ftell",  (uintptr_t)&ftell_locked },
  { "fwrite", (uintptr_t)&fwrite_diag },
  { "mkdir",  (uintptr_t)&mkdir },
  { "read",   (uintptr_t)&read_locked },
  { "remove", (uintptr_t)&remove },
  { "rename", (uintptr_t)&rename },

};

const size_t dynlib_numfunctions = sizeof(dynlib_functions) / sizeof(*dynlib_functions);

/* dlsym() backing for the module. */
uintptr_t dynlib_find_export(const char *name) {
  DynLibFunction *f = so_find_import(dynlib_functions, (int)dynlib_numfunctions, name);
  return f ? f->func : 0;
}
